#!/bin/bash
# find_schema_tables.sh - Script to identify schemas and their tables in codebases
# Created by ModelContextProtocol (MCP)

# Source the config file if it exists
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [ -f "$SCRIPT_DIR/../config.sh" ]; then
    source "$SCRIPT_DIR/../config.sh"
fi

# Set variables with defaults that can be overridden
TARGET_DIR="${1:-${DEFAULT_CODE_DIR:-/var/www/html}}"
OUTPUT_DIR="${2:-${DEFAULT_OUTPUT_DIR:-$SCRIPT_DIR/output}}"
RESULTS_FILE="$OUTPUT_DIR/schema_tables_inventory.md"

# Create output directory if it doesn't exist
mkdir -p "$OUTPUT_DIR"

echo "# Schema and Tables Inventory" > "$RESULTS_FILE"
echo "Generated on $(date)" >> "$RESULTS_FILE"
echo "" >> "$RESULTS_FILE"
echo "## Search Process" >> "$RESULTS_FILE"
echo "This report was generated by searching for schema and table references in SQL files." >> "$RESULTS_FILE"
echo "" >> "$RESULTS_FILE"

# Create list of SQL files
echo "Finding SQL files..." >> "$RESULTS_FILE"
find "$TARGET_DIR" -name "*.sql" | grep -v "node_modules" > "$OUTPUT_DIR/sql_files.txt"
echo "Found $(wc -l < "$OUTPUT_DIR/sql_files.txt") SQL files" >> "$RESULTS_FILE"
echo "" >> "$RESULTS_FILE"

# Search for CREATE SCHEMA statements
echo "## Schemas Identified" >> "$RESULTS_FILE"
echo "Searching for schema definitions..." 

grep -l "CREATE SCHEMA" $(cat "$OUTPUT_DIR/sql_files.txt") | sort > "$OUTPUT_DIR/schema_files.txt"

# Extract schema names
echo "The following schemas were identified:" >> "$RESULTS_FILE"
echo "" >> "$RESULTS_FILE"

grep -h "CREATE SCHEMA" $(cat "$OUTPUT_DIR/schema_files.txt") | \
  sed -E 's/CREATE SCHEMA (IF NOT EXISTS )?([a-zA-Z0-9_]+).*/\2/' | \
  sort | uniq | \
  awk '{print "- " $0}' >> "$RESULTS_FILE"

echo "" >> "$RESULTS_FILE"

# Search for CREATE TABLE statements
echo "## Tables by Schema" >> "$RESULTS_FILE"
echo "" >> "$RESULTS_FILE"

# First get all CREATE TABLE statements
echo "Searching for table definitions..."
grep -l "CREATE TABLE" $(cat "$OUTPUT_DIR/sql_files.txt") | sort > "$OUTPUT_DIR/table_files.txt"

# Extract schema and table names
echo "### Tables with Schema Prefix" >> "$RESULTS_FILE"
echo "" >> "$RESULTS_FILE"

grep -h "CREATE TABLE" $(cat "$OUTPUT_DIR/table_files.txt") | \
  grep "\." | \
  sed -E 's/CREATE TABLE (IF NOT EXISTS )?([a-zA-Z0-9_]+)\.([a-zA-Z0-9_]+).*/\2|\3/' | \
  sort | uniq > "$OUTPUT_DIR/schema_tables.txt"

# Print each schema and its tables
current_schema=""
while IFS="|" read -r schema table; do
  if [ "$schema" != "$current_schema" ]; then
    echo "#### $schema Schema" >> "$RESULTS_FILE"
    echo "" >> "$RESULTS_FILE"
    current_schema="$schema"
  fi
  echo "- $table" >> "$RESULTS_FILE"
done < "$OUTPUT_DIR/schema_tables.txt"

echo "" >> "$RESULTS_FILE"

# Extract tables without explicit schemas
echo "### Tables without Explicit Schema" >> "$RESULTS_FILE"
echo "These tables appear without an explicit schema prefix (likely using the default schema):" >> "$RESULTS_FILE"
echo "" >> "$RESULTS_FILE"

grep -h "CREATE TABLE" $(cat "$OUTPUT_DIR/table_files.txt") | \
  grep -v "\." | \
  sed -E 's/CREATE TABLE (IF NOT EXISTS )?([a-zA-Z0-9_]+).*/\2/' | \
  sort | uniq | \
  grep -v "^$" | \
  awk '{print "- " $0}' >> "$RESULTS_FILE"

echo "" >> "$RESULTS_FILE"

# Searching for common patterns that might indicate relationships
echo "## Table Relationships" >> "$RESULTS_FILE"
echo "Identifying potential table relationships based on foreign key constraints and join patterns..." >> "$RESULTS_FILE"
echo "" >> "$RESULTS_FILE"

# Foreign key constraints
echo "### Foreign Key Constraints" >> "$RESULTS_FILE"
echo "" >> "$RESULTS_FILE"

grep -h "FOREIGN KEY" $(cat "$OUTPUT_DIR/sql_files.txt") | \
  sed -E 's/.*FOREIGN KEY.*REFERENCES ([a-zA-Z0-9_\.]+).*/\1/' | \
  sort | uniq | head -20 | \
  awk '{print "- " $0}' >> "$RESULTS_FILE"

echo "..." >> "$RESULTS_FILE"
echo "" >> "$RESULTS_FILE"

# Find JOIN statements in views
echo "### JOIN Patterns in Views" >> "$RESULTS_FILE"
echo "" >> "$RESULTS_FILE"

grep -h "JOIN" $(cat "$OUTPUT_DIR/sql_files.txt") | grep -i "view" | \
  sort | uniq | head -20 | \
  awk '{print "- " $0}' >> "$RESULTS_FILE"

echo "..." >> "$RESULTS_FILE"
echo "" >> "$RESULTS_FILE"

# Summary
echo "## Summary" >> "$RESULTS_FILE"
echo "This report represents a high-level overview of schemas and tables found in the codebase. Use this as a starting point for more detailed analysis." >> "$RESULTS_FILE"
echo "" >> "$RESULTS_FILE"
echo "For further investigation, consider:" >> "$RESULTS_FILE"
echo "1. Analyzing table columns for shared IDs and references" >> "$RESULTS_FILE"
echo "2. Examining SQL queries to understand data flow" >> "$RESULTS_FILE"
echo "3. Creating a more detailed entity-relationship diagram" >> "$RESULTS_FILE"
echo "" >> "$RESULTS_FILE"
echo "Report generated by ModelContextProtocol (MCP)" >> "$RESULTS_FILE"

echo "Schema and tables inventory completed. See $RESULTS_FILE for results."
